name: CI Básico

on:
  push:
    branches: [ "main" ]  # Solo se activa en main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4  # Descarga el código

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn package  # Solo compila
